
module.exports = [{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'cliff jump',
    description: 'Jump  off cliff',
    img: 'https://img1.10bestmedia.com/Images/Photos/317046/photo_54_990x660.jpg',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Go to Paris',
    description: 'Travel to Paris and explore',
    img: 'https://theplanetd.com/images/Where-to-Stay-in-Paris-Neighborhoods.jpg',
    price: 100,
    completed: true, 
},
{
    season: 'Spring',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Winter',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
];