
module.exports = [{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'cliff jump',
    description: 'Jump  off cliff',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
{
    season: 'Summer',
    title: 'Sky Diving',
    description: 'Jump out of an airplane',
    img: 'https://images.pexels.com/photos/739671/pexels-photo-739671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    price: 100,
    completed: true, 
},
];